AllCops:
  TargetRubyVersion: 3
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/*/*.rb

Naming/VariableNumber:
  EnforcedStyle: snake_case
