version: '3.4'

volumes:
  dbdata:
    driver: local

services:
  db:
    image: postgres:13
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: usrname_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superSecret123
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=secret123
      - WEBPACKER_DEV_SERVER_HOST=webpack
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - webpack

  worker:
    build: .
    depends_on:
      - db
    command: "bin/rails jobs:work"
    volumes:
      - .:/usr/src/app
    environment:
      - RAILS_ENV=development

  webpack:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/usr/src/app
    ports:
      - '3035:3035'
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
